Repository esowc/ml_drought, pull requests merged in 2019-10, with the labels that each got.

#125 Add XGBoost
  src/models/__init__.py
  src/models/base.py
  src/models/gbdt.py
  tests/models/__init__.py
  tests/models/test_gbdt.py
Labels: modelling

#121 Notebooks/analysis
  notebooks/docs/00_pipeline.ipynb
  notebooks/docs/Analysis.ipynb
  notebooks/docs/Pipeline.ipynb
  notebooks/docs/img/ealstm_lstm.png
  notebooks/docs/pipeline_components/00_Directory_Structure.ipynb
  notebooks/docs/pipeline_components/01_Exporters.ipynb
  notebooks/docs/pipeline_components/02_Preprocessors.ipynb
  notebooks/docs/pipeline_components/03_Engineer.ipynb
  notebooks/docs/pipeline_components/04_Models.ipynb
  notebooks/docs/pipeline_components/05_Analysis.ipynb
  notebooks/docs/pipeline_components/06_Test.ipynb
  notebooks/draft/15_gt_ealstm.ipynb
  notebooks/draft/17_tl_analysis_test.ipynb
  notebooks/draft/18_tl_analysis_chirps_grid.ipynb
  notebooks/draft/19_tl_ERA5grid.ipynb
  scripts/preprocess.py
  src/analysis/__init__.py
  src/analysis/evaluation.py
  src/analysis/indices/base.py
  src/analysis/region_analysis/base.py
  src/analysis/region_analysis/region_geo_plotter.py
  src/models/base.py
  src/models/neural_networks/base.py
Labels: analysis

#128 Envs and codecov
  .travis.yml
  Dockerfile
  README.md
  environment.mac.yml
  environment.ubuntu.cpu.yml
  environment.yml
  pytest.ini
Labels: documentation
