Repository esowc/ml_drought, pull requests merged in 2019-07, with the labels that each got.

#46 Add shap explanations to models
  .gitignore
  environment.mac.yml
  environment.ubuntu.cpu.yml
  scripts/models.py
  src/analysis/__init__.py
  src/analysis/plot_shap.py
  src/models/base.py
  src/models/linear_network.py
  src/models/regression.py
  tests/models/test_linear_network.py
  tests/models/test_regression.py
Labels: model validation, modelling

#51 Revert to best model during early stopping
  src/models/linear_network.py
  src/models/regression.py
Labels: model validation, modelling

#53 Add prediction month to the models
  scripts/models.py
  src/models/base.py
  src/models/data.py
  src/models/linear_network.py
  src/models/parsimonious.py
  src/models/regression.py
  src/models/utils.py
  tests/models/test_data.py
  tests/models/test_linear_network.py
  tests/models/test_regression.py
  tests/models/test_utils.py
Labels: modelling

#55 Allow models to define prediction months
  src/models/base.py
  src/models/data.py
  src/models/linear_network.py
  src/models/parsimonious.py
  src/models/regression.py
  tests/models/test_data.py
  tests/models/test_regression.py
Labels: modelling

#57 Monthly mean preprocessor for ERA5 data
  scripts/export.py
  src/exporters/cds.py
  src/preprocess/__init__.py
  src/preprocess/era5.py
  tests/preprocess/test_era5.py
Labels: preprocess

#58 Add an RNN
  scripts/models.py
  src/models/__init__.py
  src/models/neural_networks/__init__.py
  src/models/neural_networks/base.py
  src/models/neural_networks/linear_network.py
  src/models/neural_networks/rnn.py
  src/models/regression.py
  tests/models/neural_networks/__init__.py
  tests/models/neural_networks/test_linear_network.py
  tests/models/neural_networks/test_rnn.py
Labels: modelling

#60 Make the training data 12 months by default
  src/engineer/engineer.py
  tests/engineer/test_nowcast.py
  tests/engineer/test_one_month_forecast.py
Labels: feature engineering

#59 Include surrounding pixels in the model
  src/analysis/plot_shap.py
  src/models/base.py
  src/models/data.py
  src/models/neural_networks/base.py
  src/models/neural_networks/linear_network.py
  src/models/neural_networks/rnn.py
  src/models/regression.py
  tests/models/neural_networks/test_linear_network.py
  tests/models/test_data.py
  tests/models/test_regression.py
Labels: modelling

#49 Add nowcasting option to the pipeline
  .gitignore
  scripts/engineer.py
  scripts/models.py
  src/analysis/event_detector.py
  src/analysis/plot_shap.py
  src/models/base.py
  src/models/data.py
  src/models/neural_networks/base.py
  src/models/neural_networks/linear_network.py
  src/models/neural_networks/rnn.py
  src/models/parsimonious.py
  src/models/regression.py
  src/models/utils.py
  src/utils.py
  tests/models/neural_networks/test_linear_network.py
  tests/models/neural_networks/test_rnn.py
  tests/models/test_data.py
  tests/models/test_parsimonious.py
  tests/models/test_regression.py
  tests/models/test_utils.py
Labels: feature engineering, modelling

#64 [minor] Add nonlinearities to the final dense layers of the RNN
  scripts/models.py
  src/models/neural_networks/base.py
  src/models/neural_networks/linear_network.py
  src/models/neural_networks/rnn.py
  tests/models/neural_networks/test_rnn.py
Labels: modelling

#68 [minor] Properly label losses when training neural networks
  src/models/neural_networks/base.py
  tests/models/neural_networks/test_linear_network.py
  tests/models/neural_networks/test_rnn.py
Labels: model validation

#66 Fix validation bug in the nowcaster
  scripts/engineer.py
  scripts/models.py
  src/models/neural_networks/base.py
  src/models/regression.py
Labels: modelling

#67 Make it easy to save and load models
  src/models/__init__.py
  src/models/neural_networks/linear_network.py
  src/models/neural_networks/rnn.py
  src/models/regression.py
  tests/models/__init__.py
  tests/models/neural_networks/test_linear_network.py
  tests/models/neural_networks/test_rnn.py
  tests/models/test_regression.py
Labels: model validation, modelling

#70 Allow models to see latitude and longitude of target pixels
  src/models/base.py
  src/models/data.py
  src/models/neural_networks/base.py
  src/models/neural_networks/linear_network.py
  src/models/neural_networks/rnn.py
  src/models/regression.py
  tests/models/neural_networks/test_linear_network.py
  tests/models/neural_networks/test_rnn.py
  tests/models/test_data.py
  tests/models/test_regression.py
Labels: modelling

#75 Updates to the engineer
  src/engineer/__init__.py
  src/engineer/base.py
  src/engineer/nowcast.py
  src/engineer/one_month_forecast.py
  tests/engineer/test_base.py
  tests/engineer/test_engineer.py
  tests/engineer/test_nowcast.py
  tests/engineer/test_one_month_forecast.py
Labels: feature engineering

#65 Allow models to specify variables to ignore
  src/models/base.py
  src/models/data.py
  src/models/neural_networks/base.py
  src/models/neural_networks/linear_network.py
  src/models/neural_networks/rnn.py
  src/models/regression.py
  tests/models/neural_networks/test_linear_network.py
  tests/models/neural_networks/test_rnn.py
  tests/models/test_data.py
  tests/models/test_regression.py
Labels: modelling
